// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241008195441_Seed2")]
    partial class Seed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Competitor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrintInitialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("ScoreboardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("TvInitialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TvName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = "SWE-1001",
                            CompetitorType = "A",
                            Country = "SWE",
                            PrintName = "Kenny Westermark (PRINT)",
                            ScoreboardName = "K. Westgrund (SB)",
                            TvName = "K. WEST (TV)"
                        },
                        new
                        {
                            Id = "SWE-1002",
                            CompetitorType = "A",
                            Country = "SWE",
                            PrintName = "Andreas Boström (PRINT)",
                            ScoreboardName = "A. Boström (SB)",
                            TvName = "A. BOST (TV)"
                        });
                });

            modelBuilder.Entity("Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discipline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SportClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Models.GoldenPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoldenPoint");
                });

            modelBuilder.Entity("Models.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AwayCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HomeCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Mat")
                        .HasColumnType("int");

                    b.Property<string>("MatchConfigurationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PenaltiesId")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("RefereeAssignmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("RoundTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayCompetitorId");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("EventId");

                    b.HasIndex("HomeCompetitorId");

                    b.HasIndex("MatchConfigurationId");

                    b.HasIndex("PenaltiesId");

                    b.HasIndex("RefereeAssignmentId")
                        .IsUnique()
                        .HasFilter("[RefereeAssignmentId] IS NOT NULL");

                    b.HasIndex("ResultId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ScoreId");

                    b.HasIndex("SessionId");

                    b.ToTable("Matchs");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AwayCompetitorId = "SWE-1002",
                            HomeCompetitorId = "SWE-1001",
                            Mat = 1,
                            Number = "1-1",
                            Phase = 7
                        });
                });

            modelBuilder.Entity("Models.MatchAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AwayCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hitlevel")
                        .HasColumnType("int");

                    b.Property<string>("HomeCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PenaltiesId")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("RoundTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScoreId")
                        .HasColumnType("int");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayCompetitorId");

                    b.HasIndex("HomeCompetitorId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PenaltiesId");

                    b.HasIndex("ScoreId");

                    b.ToTable("MatchActions");
                });

            modelBuilder.Entity("Models.MatchConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GoldenPointId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDifference")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPenalties")
                        .HasColumnType("int");

                    b.Property<int?>("Rounds")
                        .HasColumnType("int");

                    b.Property<int>("Rules")
                        .HasColumnType("int");

                    b.Property<int?>("ThresholdsId")
                        .HasColumnType("int");

                    b.Property<int>("TimingId")
                        .HasColumnType("int");

                    b.Property<int?>("VideoReplayQuotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoldenPointId");

                    b.HasIndex("ThresholdsId");

                    b.HasIndex("TimingId");

                    b.HasIndex("VideoReplayQuotaId");

                    b.ToTable("MatchConfigurations");
                });

            modelBuilder.Entity("Models.MatchInternalResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayType")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchInternalResult");
                });

            modelBuilder.Entity("Models.MatchRefereeAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefCRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefJ1Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefJ2Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefJ3Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefRJId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefTAId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RefCRId");

                    b.HasIndex("RefJ1Id");

                    b.HasIndex("RefJ2Id");

                    b.HasIndex("RefJ3Id");

                    b.HasIndex("RefRJId");

                    b.HasIndex("RefTAId");

                    b.ToTable("MatchRefereeAssignments");
                });

            modelBuilder.Entity("Models.MatchResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AwayCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeCompetitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PenaltiesId")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayCompetitorId");

                    b.HasIndex("HomeCompetitorId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PenaltiesId");

                    b.HasIndex("ResultId");

                    b.HasIndex("ScoreId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("Models.MatchSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduledStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchSchedule");
                });

            modelBuilder.Entity("Models.MatchScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Away")
                        .HasColumnType("int");

                    b.Property<int?>("Home")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchScore");
                });

            modelBuilder.Entity("Models.MedalWinner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("MedalWinners");
                });

            modelBuilder.Entity("Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Models.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainRole")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassportFamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportGivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredGivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintInitialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScoreboardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TvInitialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TvName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleStatus")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Models.Thresholds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Body")
                        .HasColumnType("int");

                    b.Property<int?>("Head")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Thresholds");
                });

            modelBuilder.Entity("Models.Timing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Injury")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Round")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timing");
                });

            modelBuilder.Entity("Models.Competitor", b =>
                {
                    b.HasOne("Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.Navigation("Event");

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Models.Match", b =>
                {
                    b.HasOne("Models.Competitor", "AwayCompetitor")
                        .WithMany()
                        .HasForeignKey("AwayCompetitorId");

                    b.HasOne("Models.Competitor", null)
                        .WithMany("Matches")
                        .HasForeignKey("CompetitorId");

                    b.HasOne("Models.Event", "Event")
                        .WithMany("Matches")
                        .HasForeignKey("EventId");

                    b.HasOne("Models.Competitor", "HomeCompetitor")
                        .WithMany()
                        .HasForeignKey("HomeCompetitorId");

                    b.HasOne("Models.MatchConfiguration", "MatchConfiguration")
                        .WithMany()
                        .HasForeignKey("MatchConfigurationId");

                    b.HasOne("Models.MatchScore", "Penalties")
                        .WithMany()
                        .HasForeignKey("PenaltiesId");

                    b.HasOne("Models.MatchRefereeAssignment", "RefereeAssignment")
                        .WithOne("Match")
                        .HasForeignKey("Models.Match", "RefereeAssignmentId");

                    b.HasOne("Models.MatchInternalResult", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.HasOne("Models.MatchSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("Models.MatchScore", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId");

                    b.HasOne("Models.Session", "Session")
                        .WithMany("Matches")
                        .HasForeignKey("SessionId");

                    b.Navigation("AwayCompetitor");

                    b.Navigation("Event");

                    b.Navigation("HomeCompetitor");

                    b.Navigation("MatchConfiguration");

                    b.Navigation("Penalties");

                    b.Navigation("RefereeAssignment");

                    b.Navigation("Result");

                    b.Navigation("Schedule");

                    b.Navigation("Score");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Models.MatchAction", b =>
                {
                    b.HasOne("Models.Competitor", "AwayCompetitor")
                        .WithMany()
                        .HasForeignKey("AwayCompetitorId");

                    b.HasOne("Models.Competitor", "HomeCompetitor")
                        .WithMany()
                        .HasForeignKey("HomeCompetitorId");

                    b.HasOne("Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.HasOne("Models.MatchScore", "Penalties")
                        .WithMany()
                        .HasForeignKey("PenaltiesId");

                    b.HasOne("Models.MatchScore", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId");

                    b.Navigation("AwayCompetitor");

                    b.Navigation("HomeCompetitor");

                    b.Navigation("Match");

                    b.Navigation("Penalties");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Models.MatchConfiguration", b =>
                {
                    b.HasOne("Models.GoldenPoint", "GoldenPoint")
                        .WithMany()
                        .HasForeignKey("GoldenPointId");

                    b.HasOne("Models.Thresholds", "Thresholds")
                        .WithMany()
                        .HasForeignKey("ThresholdsId");

                    b.HasOne("Models.Timing", "Timing")
                        .WithMany()
                        .HasForeignKey("TimingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.MatchScore", "VideoReplayQuota")
                        .WithMany()
                        .HasForeignKey("VideoReplayQuotaId");

                    b.Navigation("GoldenPoint");

                    b.Navigation("Thresholds");

                    b.Navigation("Timing");

                    b.Navigation("VideoReplayQuota");
                });

            modelBuilder.Entity("Models.MatchRefereeAssignment", b =>
                {
                    b.HasOne("Models.Participant", "RefCR")
                        .WithMany()
                        .HasForeignKey("RefCRId");

                    b.HasOne("Models.Participant", "RefJ1")
                        .WithMany()
                        .HasForeignKey("RefJ1Id");

                    b.HasOne("Models.Participant", "RefJ2")
                        .WithMany()
                        .HasForeignKey("RefJ2Id");

                    b.HasOne("Models.Participant", "RefJ3")
                        .WithMany()
                        .HasForeignKey("RefJ3Id");

                    b.HasOne("Models.Participant", "RefRJ")
                        .WithMany()
                        .HasForeignKey("RefRJId");

                    b.HasOne("Models.Participant", "RefTA")
                        .WithMany()
                        .HasForeignKey("RefTAId");

                    b.Navigation("RefCR");

                    b.Navigation("RefJ1");

                    b.Navigation("RefJ2");

                    b.Navigation("RefJ3");

                    b.Navigation("RefRJ");

                    b.Navigation("RefTA");
                });

            modelBuilder.Entity("Models.MatchResult", b =>
                {
                    b.HasOne("Models.Competitor", "AwayCompetitor")
                        .WithMany()
                        .HasForeignKey("AwayCompetitorId");

                    b.HasOne("Models.Competitor", "HomeCompetitor")
                        .WithMany()
                        .HasForeignKey("HomeCompetitorId");

                    b.HasOne("Models.Match", "Match")
                        .WithMany("Results")
                        .HasForeignKey("MatchId");

                    b.HasOne("Models.MatchScore", "Penalties")
                        .WithMany()
                        .HasForeignKey("PenaltiesId");

                    b.HasOne("Models.MatchInternalResult", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.HasOne("Models.MatchScore", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId");

                    b.Navigation("AwayCompetitor");

                    b.Navigation("HomeCompetitor");

                    b.Navigation("Match");

                    b.Navigation("Penalties");

                    b.Navigation("Result");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Models.MedalWinner", b =>
                {
                    b.HasOne("Models.Event", null)
                        .WithMany("MedalWinners")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Models.Participant", b =>
                {
                    b.HasOne("Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Models.Competitor", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Models.Event", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("MedalWinners");
                });

            modelBuilder.Entity("Models.Match", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Models.MatchRefereeAssignment", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("Models.Session", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
